# SPDX-License-Identifier: MPL-2.0
"""docs/cli.md is generated where a command line exists, not only where the file does.

Relayed by a product: "docs/cli.md is only generated if the file already
exists". Measured, and worse than reported -- the note that explains an
absent reference was written for the other case, so a product that pinned
maelys-cli and shipped a command got no reference **and** no word about it.
"""
from __future__ import annotations

import json
import unittest

from test_maelys_release import MODULE, Product


GENERATOR = '''\
import json, sys
argv = sys.argv[1:]
options = {argv[i]: argv[i + 1] for i in range(0, len(argv) - 1, 2) if argv[i].startswith("--")}
programs = [word for word in argv if not word.startswith("--")
            and word not in options.values()]
open(options["--markdown"], "w").write(
    "<!-- generated from describe; do not edit -->\\n\\n# CLI\\n\\n" + " ".join(programs) + "\\n")
open(options["--json"], "w").write(json.dumps({"programs": programs}) + "\\n")
'''


class CliReferenceTest(unittest.TestCase):
    def setUp(self) -> None:
        self.product = Product()
        self.addCleanup(self.product.close)
        self.dir = str(self.product.dir)

    def declarations(self):
        return MODULE.read_declarations(self.product.dir, "maelys-fixture", "maelys-release")

    def test_a_product_with_a_command_gets_its_reference_written(self) -> None:
        self.product.write(MODULE.CLI_GENERATOR, GENERATOR)
        self.assertFalse((self.product.dir / MODULE.CLI_REFERENCE).is_file())
        decl = self.declarations()
        self.assertTrue(decl.generates_reference)
        self.assertTrue([check for check in decl.checks
                         if check["message"].startswith(f"{MODULE.CLI_REFERENCE} is generated by the socle")])
        self.product.run("adopt", self.dir, "--apply")
        written = self.product.read(MODULE.CLI_REFERENCE)
        self.assertIn("generated from describe", written)
        # The fixture's command formula, and not its library one.
        self.assertIn("maelys-fixture", written)
        self.assertNotIn("libmaelys-fixture", written)
        self.assertEqual(json.loads(self.product.read(MODULE.CLI_CONTRACT))["programs"], ["maelys-fixture"])

    def test_a_generator_that_cannot_run_writes_no_empty_file(self) -> None:
        """What "the generator did not run here" used to leave behind, for a
        product with no reference yet, was an empty docs/cli.md."""
        self.product.write(MODULE.CLI_GENERATOR, "import sys\nsys.exit(1)\n")
        # The note comes from the rendering, which happens when the socle
        # stages what it would write -- not from reading the declarations.
        data = self.product.json("adopt", self.dir, "--apply")["data"]
        self.assertFalse((self.product.dir / MODULE.CLI_REFERENCE).is_file())
        self.assertFalse((self.product.dir / MODULE.CLI_CONTRACT).is_file())
        notes = [check["message"] for check in data["checks"] if check["status"] == "note"]
        self.assertTrue([note for note in notes if "the generator did not run here" in note], notes)
        self.assertEqual([entry for entry in data["files"] if entry["path"] == MODULE.CLI_REFERENCE], [])

    def test_a_library_on_the_framework_is_told_why_it_has_none(self) -> None:
        """Its templates are all lib*: there is no command to describe."""
        (self.product.dir / "packaging" / "homebrew" / "maelys-fixture.rb.in").unlink()
        self.product.write(MODULE.CLI_GENERATOR, GENERATOR)
        decl = self.declarations()
        self.assertFalse(decl.generates_reference)
        notes = [check["message"] for check in decl.checks if check["status"] == "note"]
        self.assertTrue([note for note in notes
                         if note.startswith(f"no {MODULE.CLI_REFERENCE}") and "declares no command" in note], notes)

    def test_a_product_that_already_carries_one_keeps_being_generated(self) -> None:
        """The case that worked, held: nothing here is taken away."""
        self.product.write(MODULE.CLI_GENERATOR, GENERATOR)
        self.product.write(MODULE.CLI_REFERENCE, "<!-- generated from describe; do not edit -->\n\n# old\n")
        self.product.run("adopt", self.dir, "--apply")
        self.assertIn("# CLI", self.product.read(MODULE.CLI_REFERENCE))
