#!/usr/bin/env python3
# SPDX-License-Identifier: MPL-2.0
"""Explicit bootstrap/refresh of API inputs from a clean, named source commit.

This tool alone can read GitHub. It cannot issue a GitHub write or run a
product publication. Normal CI uses capture_api.py, which cannot call gh/git.
The responses cache preserves every first live reading across interrupted
recordings; refreshing live data requires a different, explicit cache path.
"""
from __future__ import annotations

import argparse
import contextlib
import copy
import datetime
import hashlib
import io
import json
import os
import pathlib
import re
import shutil
import subprocess
import tempfile

import capture_api as replay

REPOSITORIES = ('maelys-dev/maelys-system', 'maelys-dev/agent-cli-spec')
DATE = '2026-09-16T00:00:00+0000'


def git(project, *args):
    return subprocess.run(['git', '-C', str(project.resolve()), *args], check=True, capture_output=True,
                          text=True, env={**os.environ, 'GIT_CONFIG_GLOBAL': os.devnull,
                          'GIT_CONFIG_SYSTEM': os.devnull, 'GIT_CONFIG_NOSYSTEM': '1',
                          'GIT_AUTHOR_DATE': DATE, 'GIT_COMMITTER_DATE': DATE}).stdout.strip()


def safe_git(command):
    prefixes = (['git', 'remote', 'get-url', 'origin'], ['git', 'config', '--get'],
                ['git', 'tag', '--list'], ['git', 'rev-parse'], ['git', 'grep'],
                ['git', 'describe', '--tags', '--abbrev=0'], ['git', 'cat-file', '-t'],
                ['git', 'cat-file', '-p'], ['git', 'merge-base', '--is-ancestor'])
    return any(command[:len(prefix)] == prefix for prefix in prefixes)


def fixture(module, parent, repository, commit, kind):
    project = parent / repository.split('/')[-1]
    project.mkdir()
    files = {'VERSION': '1.2.3\n', 'CHANGELOG.md': '# Changelog\n\n## 1.2.3 — 2026-09-16\n\n- Fixture.\n',
             'maelys-release.conf': '[gate]\nnone\n', 'scripts/package-release.sh': '#!/bin/sh\nexit 0\n'}
    for name, value in files.items():
        path = project / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(value, encoding='utf-8')
    (project / 'scripts/package-release.sh').chmod(0o755)
    # Build managed files using the named, clean implementation, before origin
    # exists. This changes only a temporary product, never a fleet checkout.
    original = module.host.HOST
    class Bootstrap(module.Host):
        def read(self, path):
            raise AssertionError(f'fixture setup attempted GitHub: {path}')
        def which(self, name):
            return None
    module.host.HOST = Bootstrap()
    try:
        out, err = io.StringIO(), io.StringIO()
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
            code = module.APP.main(['adopt', str(project), '--mechanism', 'maelys-release', '--apply',
                                    '--socle-sha', commit, '--socle-tag', 'v' + module.socle_version(),
                                    '--format', 'json'])
        if code:
            raise RuntimeError(err.getvalue())
    finally:
        module.host.HOST = original
    if kind == 'old-pin':
        for path in (project / '.github/workflows').glob('*.yml'):
            text = path.read_text(encoding='utf-8')
            path.write_text(text.replace(commit + ' # v' + module.socle_version(), '0' * 40 + ' # v0.57.2'), encoding='utf-8')
    if kind.startswith('migration'):
        (project / 'docs').mkdir(exist_ok=True)
        for name, text in {'guide.md': '# Internal guide\n\nA document to move.\n',
                           'public.md': '# Public promise\n',
                           'generated.md': '<!-- Generated by fixture. Do not edit. -->\n',
                           'unlisted.md': '# Unlisted prose\n', 'data.json': '{}\n'}.items():
            (project / 'docs' / name).write_text(text, encoding='utf-8')
        (project / 'README.md').write_text('[guide](docs/guide.md)\n', encoding='utf-8')
        licensing = project / 'LICENSING.md'
        licensing.write_text(licensing.read_text(encoding='utf-8') + '\n- [Public promise](docs/public.md).\n', encoding='utf-8')
        record = {'repository': project.name, 'path': 'docs/guide.md',
                  'destination': f'golden-docs/{project.name}/guide.md'}
        if kind == 'migration-foreign':
            record['repository'] = 'another-product'
        if kind == 'migration-wrong-destination':
            record['destination'] = 'elsewhere/guide.md'
        (project / 'documents.jsonl').write_text(json.dumps(record) + '\n', encoding='utf-8')
    git(project, 'init', '-q', '-b', 'main')
    git(project, 'config', 'user.name', 'Golden fixture')
    git(project, 'config', 'user.email', 'golden@example.invalid')
    git(project, 'config', 'commit.gpgsign', 'false')
    git(project, 'add', '-A')
    git(project, 'commit', '-q', '-m', 'Frozen API fixture')
    git(project, 'remote', 'add', 'origin', 'https://github.com/' + repository + '.git')
    git(project, 'remote', 'set-url', '--push', 'origin', 'disabled://golden-read-only')
    git(project, 'config', 'tag.gpgsign', 'true')
    git(project, 'config', 'gpg.format', 'ssh')
    git(project, 'config', 'user.signingkey', 'golden-fixture-key-not-used')
    return project


def scenarios():
    cases = []
    def add(name, repository, profile, command, kind='current-pin', options=()):
        for fmt in ('json', 'text'):
            cases.append({'id': name + '-' + fmt, 'repository': repository, 'profile': profile,
                          'command': command, 'fixture': kind, 'options': list(options), 'format': fmt})
    system, ruleset = REPOSITORIES
    for name, repository, profile in (('classic', system, 'live'), ('ruleset', ruleset, 'live'),
                                      ('open', system, 'open'), ('unreadable', system, 'unreadable'),
                                      ('partial-observations', system, 'partial')):
        add('protect-' + name, repository, profile, 'protect')
    add('protect-narrow-plan', system, 'live', 'protect', options=('--without-legs',))
    for name, repository, profile in (('classic', system, 'live'), ('ruleset', ruleset, 'live'),
                                      ('private', system, 'private'), ('open', system, 'open'),
                                      ('missing-environment', system, 'missing-environment')):
        add('preflight-' + name, repository, profile, 'preflight')
    for profile in ('live', 'private', 'private-open', 'private-unreadable'):
        for command in ('adopt', 'check'):
            add('current-' + profile + '-' + command, system, profile, command, kind='old-pin')
    for name, repository, profile in (('classic-allowed', system, 'live'), ('ruleset-allowed', ruleset, 'live'),
                                      ('classic-refused', system, 'stale'), ('ruleset-refused', ruleset, 'stale'),
                                      ('unreadable', system, 'unreadable')):
        add('adoption-guard-' + name, repository, profile, 'adopt', kind='old-pin', options=('--apply',))
    for kind in ('migration', 'migration-foreign', 'migration-wrong-destination'):
        add(kind, system, 'live', 'migrate', kind=kind)
    return cases


class Responses:
    def __init__(self, original, cache):
        self.original, self.cache = original, cache
        self.live = replay.read_json(cache) if cache.exists() else {}
        self.used = {}

    def read(self, endpoint, profile):
        product_read = any(endpoint == 'repos/' + repo or endpoint.startswith('repos/' + repo + '/')
                           for repo in REPOSITORIES)
        tap_read = re.fullmatch(r'repos/maelys-dev/homebrew-tap/contents/Formula(?:/[A-Za-z0-9_.-]+\.rb)?', endpoint)
        if not product_read and not tap_read:
            raise AssertionError(f'API endpoint outside the recording scope: {endpoint}')
        if endpoint not in self.live:
            state, body = self.original.read(endpoint)
            if state not in ('ok', 'absent'):
                raise RuntimeError(f'live GET {endpoint}: {state}; do not record a transient failure as live truth')
            self.live[endpoint] = {'state': state, 'body': body, 'provenance': {'kind': 'live', 'method': 'GET',
                'endpoint': endpoint, 'recordedAt': datetime.datetime.now(datetime.timezone.utc).isoformat()}}
            replay.write_json(self.cache, self.live)
        answer = copy.deepcopy(self.live[endpoint])
        self.used[endpoint] = copy.deepcopy(answer)
        changes = []
        if profile.startswith('private') and endpoint.count('/') == 2:
            answer['body']['visibility'], answer['body']['private'] = 'private', True
            changes.append('repository visibility becomes private')
        if profile in ('open', 'private-open'):
            if endpoint.endswith('/protection'):
                answer.update(state='absent', body=None)
                changes.append('classic protection is absent')
            elif '/rules/branches/' in endpoint:
                answer.update(state='ok', body=[])
                changes.append('no branch rules apply')
        if profile in ('unreadable', 'private-unreadable') and (endpoint.endswith('/protection') or '/rules/branches/' in endpoint):
            answer.update(state='unreadable', body=None)
            changes.append('protection/rules reading is unreadable')
        if profile == 'partial' and '/check-runs?' in endpoint:
            answer.update(state='unreadable', body=None)
            changes.append('check-run reading is unreadable')
        if profile == 'missing-environment' and '/environments/release' in endpoint:
            answer.update(state='absent', body=None)
            changes.append('release environment is absent')
        if profile == 'stale':
            if endpoint.endswith('/protection') and answer['state'] == 'ok':
                answer['body']['required_status_checks']['contexts'].append('check / check (retired-golden)')
                changes.append('classic protection additionally requires a retired socle leg')
            elif '/rules/branches/' in endpoint:
                for rule in answer['body'] or []:
                    if rule.get('type') == 'required_status_checks':
                        rule['parameters']['required_status_checks'].append({'context': 'check / check (retired-golden)'})
                        changes.append('ruleset additionally requires a retired socle leg')
                        break
        key = endpoint
        if changes:
            key = profile + ':' + endpoint
            answer['provenance'] = {'kind': 'derived', 'from': endpoint, 'changes': changes}
        self.used[key] = answer
        return key, answer


def recording_host(module, project, source, responses, profile):
    original = module.Host()
    class RecordingHost(module.Host):
        def __init__(self):
            self.events = []
        def which(self, name):
            if name != 'gh':
                raise AssertionError(f'unexpected tool lookup: {name}')
            value = original.which(name)
            if not value:
                raise RuntimeError('input recording requires authenticated gh')
            self.events.append({'call': {'kind': 'which', 'name': name}, 'result': value})
            return value
        def read(self, path):
            key, answer = responses.read(path, profile)
            self.events.append({'call': {'kind': 'read', 'path': path}, 'response': key})
            return answer['state'], copy.deepcopy(answer['body'])
        def run(self, command, cwd=None, env=None):
            if env is not None or cwd != project or not safe_git(command):
                raise AssertionError(f'unapproved recording process: {command!r}, {cwd}')
            done = original.run(command, cwd=cwd)
            event = {'call': {'kind': 'run', 'argv': command, 'cwd': str(cwd)},
                     'result': {'returncode': done.returncode, 'stdout': done.stdout, 'stderr': done.stderr}}
            self.events.append(replay.substitute(event, {str(project): '<PRODUCT>', str(source): '<SOCLE>'}))
            return done
        def write(self, *args, **kwargs):
            raise AssertionError('recording forbids GitHub writes')
        def stream(self, *args, **kwargs):
            raise AssertionError('recording forbids streaming processes')
        def exec(self, *args, **kwargs):
            raise AssertionError('recording forbids process replacement')
    return RecordingHost()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('output', type=pathlib.Path)
    parser.add_argument('--source', type=pathlib.Path, required=True)
    parser.add_argument('--commit', required=True)
    parser.add_argument('--responses-cache', type=pathlib.Path, required=True)
    args = parser.parse_args()
    source, output = args.source.resolve(), args.output.resolve()
    if not re.fullmatch('[0-9a-f]{40}', args.commit) or git(source, 'rev-parse', 'HEAD') != args.commit:
        parser.error('--commit must name the full HEAD of the source')
    if git(source, 'status', '--porcelain') or output.exists():
        parser.error('source must be clean and output must not exist')
    if any(name.startswith('_MAELYS_RELEASE_') for name in os.environ):
        parser.error('record outside a self-test environment')
    os.environ.update({'LANG': 'C', 'LC_ALL': 'C', 'TZ': 'UTC', 'GH_HOST': 'github.com',
                       'GIT_CONFIG_GLOBAL': os.devnull, 'GIT_CONFIG_SYSTEM': os.devnull,
                       'GIT_CONFIG_NOSYSTEM': '1', 'GIT_TERMINAL_PROMPT': '0', 'GIT_OPTIONAL_LOCKS': '0',
                       'MAELYS_RELEASE_NO_RELOCATE': '1'})
    module = replay.load_source(source)
    responses = Responses(module.Host(), args.responses_cache.resolve())
    with tempfile.TemporaryDirectory(prefix='api-record-') as directory:
        work = pathlib.Path(directory).resolve()
        stage = work / 'inputs'
        stage.mkdir()
        manifest = {'schemaVersion': 1, 'sourceCommit': args.commit, 'sourceVersion': module.socle_version(),
                    'cases': [], 'sha256': {}}
        for case in scenarios():
            folder = work / case['id']
            folder.mkdir()
            project = fixture(module, folder, case['repository'], args.commit, case['fixture'])
            files = replay.files_at(project)
            argv = [case['command'], str(project), *case['options']]
            if case['command'] in ('adopt', 'check', 'preflight'):
                argv += ['--socle-sha', args.commit, '--socle-tag', 'v' + module.socle_version()]
            if case['command'] == 'migrate':
                argv += ['--documents', str(project / 'documents.jsonl'), '--documents-repository', 'example/golden-docs']
            argv += ['--format', case['format']]
            host = recording_host(module, project, source, responses, case['profile'])
            result = replay.run_command(module, argv, project, source, host)
            path = 'cases/' + case['id'] + '.json'
            replay.write_json(stage / path, {'product': project.name, 'files': files,
                               'argv': replay.substitute(argv, {str(project): '<PRODUCT>', str(source): '<SOCLE>'}),
                               'events': host.events})
            manifest['cases'].append({**case, 'input': path})
            print(f"{case['id']}: exit {result['exitCode']}, {len(host.events)} host calls, {len(result['changedFiles'])} files changed", flush=True)
        replay.write_json(stage / 'responses.json', responses.used)
        for path in sorted(stage.rglob('*.json')):
            manifest['sha256'][path.relative_to(stage).as_posix()] = hashlib.sha256(path.read_bytes()).hexdigest()
        # The version and the changelog are inputs, not code: frozen with the
        # cases, restored by the replay, so a later cut changes nothing here.
        for relative in replay.SOCLE_INPUTS:
            path = stage / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes((source / pathlib.PurePosixPath(relative).name).read_bytes())
            manifest['sha256'][relative] = hashlib.sha256(path.read_bytes()).hexdigest()
        replay.write_json(stage / 'manifest.json', manifest)
        shutil.copytree(stage, output)
    print(f'Recorded {len(manifest["cases"])} cases; outputs must now be captured from the same source commit.')


if __name__ == '__main__':
    main()
